name: Store FB Tokens

# Controls when the workflow will run
on:

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      
      # this Action should follow steps to set up Python build environment
      - name: Install Python dependencies
        uses: py-actions/py-dependency-install@v4
        with:
          path: "requirements.txt"

      # Runs a single command using the runners shell
      - name: Tokens
        env:
            PAGE_ACCESS_TOKEN: ${{ secrets.PAGE_ACCESS_TOKEN }}
            VERIFY_TOKEN: ${{ secrets.VERIFY_TOKEN }}
        run: python main.py
